#include <stdio.h>

typedef unsigned int uint;
static const int TRUE = 1;
static const int FALSE = 0;

struct factory_entry {
	int nature;
	int item_id;
};

static const int n_factory_entries = 150;

/* generated by gen-factory-data-for-c.rb */
struct factory_entry all_entries[] = {
	{15,  1},{ 3,  2},{ 3,  3},{ 3,  4},{ 3,  5},
	{ 3,  6},{10,  7},{ 6,  8},{15,  9},{ 3, 10},
	{ 3, 11},{18, 12},{ 7, 13},{ 3, 14},{ 3, 14},
	{ 3,  4},{ 3, 15},{12, 16},{ 3, 17},{ 3, 18},
	{15, 19},{20, 20},{15, 21},{ 3, 22},{ 3, 23},
	{ 3, 24},{ 3, 24},{20,  1},{15, 14},{ 3, 25},
	{ 3, 26},{15, 27},{ 3,  6},{15, 28},{ 3, 13},
	{15, 21},{ 3, 18},{ 4, 29},{ 2, 30},{ 3, 25},
	{ 3, 31},{ 7, 16},{ 3,  2},{16,  1},{ 3, 27},
	{12,  4},{ 2, 32},{13, 13},{15, 33},{13,  6},
	{ 5,  4},{15, 27},{ 5, 19},{15, 34},{ 3, 25},
	{15, 28},{10, 21},{ 3,  1},{ 5, 35},{ 3, 36},
	{ 3, 31},{17, 32},{15, 30},{13, 37},{ 5,  4},
	{15, 35},{ 3, 38},{15, 28},{15, 39},{ 8, 34},
	{ 3, 40},{ 3,  8},{ 3, 41},{ 8, 42},{15, 14},
	{10, 43},{13, 44},{ 3, 34},{ 8, 45},{15, 44},
	{ 3, 40},{15, 27},{ 3, 36},{15, 45},{10, 27},
	{ 6, 20},{17, 43},{ 3, 36},{15, 36},{ 3, 15},
	{ 3, 46},{ 5, 47},{ 6,  9},{15, 28},{ 3, 35},
	{ 3,  8},{23, 23},{22, 26},{ 3, 48},{ 3, 49},
	{ 5, 32},{ 3, 13},{20,  4},{ 3, 41},{ 3, 17},
	{13, 27},{ 3, 46},{ 3, 17},{ 3,  6},{ 3, 45},
	{ 3, 26},{15, 50},{ 3, 32},{15, 51},{15, 26},
	{ 3, 14},{ 8, 38},{ 8,  1},{ 3, 41},{15, 32},
	{13,  2},{ 0, 13},{ 3, 51},{ 3, 34},{15, 16},
	{15, 16},{17,  2},{ 3, 26},{10,  6},{ 3, 16},
	{10,  4},{ 7, 14},{15,  7},{15, 46},{10, 46},
	{13, 13},{10, 28},{15, 31},{15,  3},{13, 36},
	{20, 46},{10, 46},{20, 34},{13, 38},{13, 26},
	{10, 28},{10, 37},{13, 39},{ 3, 34},{17, 32},
};

#define SEED_TO_RAND(seed) ((int)(seed >> 16))

static uint next_seed(uint seed) {
	return seed * 0x41C64E6D + 0x6073;
}

static uint prev_seed(uint seed) {
	return seed * 0xEEB9EB65 + 0xA3561A1;
}

static int entries_collision(struct factory_entry** entries, int l, struct factory_entry* entry) {
	int i;
	for (i = 0; i < l; i ++) {
		struct factory_entry* entry2 = entries[i];
		if (entry == entry2) return TRUE;
		if (entry->item_id == entry2->item_id) return TRUE;
	}
	return FALSE;
}

static uint get_entries_by_seed(uint seed, struct factory_entry **entries) {
	int i;
	for (i = 0; i < 6; i ++) redo: {
		struct factory_entry *entry = &all_entries[n_factory_entries - 1 - SEED_TO_RAND(seed) % n_factory_entries];
		seed = next_seed(seed);
		if (entries_collision(entries, i, entry)) {
			goto redo;
		}
		entries[i] = entry;
	}
	return seed;
}

struct entries_attr {
	int parent_id;
	int secret_id;
	uint pid;
};

static uint get_entries_attr(uint seed, struct entries_attr *attrs, struct factory_entry *entries[6]) {
	int i;
	for (i = 0; i < 6; i ++) {
		struct factory_entry *entry = entries[i];
		struct entries_attr attr;
		int nature;
		attr.parent_id = SEED_TO_RAND(seed);
		seed = next_seed(seed);
		attr.secret_id = SEED_TO_RAND(seed);
		seed = next_seed(seed);
		nature = entry->nature;
		do {
			int pid_row, pid_high;
			pid_row = SEED_TO_RAND(seed);
			seed = next_seed(seed);
			pid_high = SEED_TO_RAND(seed);
			seed = next_seed(seed);
			attr.pid = (uint)pid_high << 16 | (uint)pid_row;
		} while ((int)(attr.pid % 25) != nature);
		attrs[i] = attr;
	}
	return seed;
}

int is_shiny_attr(struct entries_attr attr) {
	return ((attr.parent_id ^ attr.secret_id ^ (int)(attr.pid >> 16) ^ (int)(attr.pid & 0xffff)) & ~7) == 0;
}

uint find_first_seed(uint seed, int *pdist) {
	int dist = -24;
	int i;
	for (i = 0; i < -dist; i ++) {
		seed = prev_seed(seed);
	}
	while (dist > -100) {
		if ((seed >> 16 & 0xff) < 24 && 0x1e4 <= (seed & 0xffff) && (seed & 0xffff) <= 0x0500) {
			*pdist = dist;
			return seed;
		}
		seed = prev_seed(seed);
		dist --;
	}
	*pdist = 0;
	return 0;
}

int is_shiny(uint seed) {
	struct factory_entry *entries[6];
	struct entries_attr attrs[6];
	seed = get_entries_by_seed(seed, entries);
	seed = get_entries_attr(seed, attrs, entries);
	{
	int i;
	for (i = 0; i < 6; i ++) {
		if (is_shiny_attr(attrs[i])) {
			return TRUE;
		}
	}
	}
	return FALSE;
}

int main(void) {
	uint i = 0;
	do {
		if (is_shiny(i)) {
			int dist;
			uint first_seed = find_first_seed(i, &dist);
			if (dist != 0) {
				printf("%#.8x: %3d %#.8x\n", i, dist, first_seed);
			}
		}
		i ++;
	} while (i != 0);
	return 0;
}
